language: java
jdk: oraclejdk8

# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - sudo docker pull takimatraining/devops-training-db
  - sudo docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify

  
# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"
  
global:
  - secure: "JjWXZY7kkAYnjDfowCH5Wr8cwiHuP8ogbF4mV98sUDcsSdR/xbozGAe8nXzi0UdT5/eWlWbI5XjVNds3/IWlsP3UOGLNWCwRtdcxa7Xb9qHV+NWGxq0sH5NzzADcUwJEj3ufYBOGXCzW4Jpn/KGH/tXUMObDkAcCojqBr4uxIGIC5AN/1GfRoKuGGbuRXwJfYlYuIZ0r8jWV/DYUsNBNPK1a+zU3VoleX4ajUDRcWnI3Eoa9WHx7p9T3BABv4tIvxEnchg5Nc13LL4Qvmgk+mbnBOwLovI6PkK8XhUQwTozcjpBb3ft+I7kohnAEnuWdDfM+HeDyGM8Ljxv/Fkq78haj83CxcouxKsQvceZjDKPUZYXCYzmBCwQ67/aX6+fEGVtaH8W+d31Nuy9/9PVrS6l03v0Ux4NPCqRVdsB/rkKgDWb/re2x13XqxhPOydNQ9zjUvSPMg3p+hvcoCAzZ7ZKE3nlTnjylx1BL5bh43k7qxGIRASUsolbDWFs6kBvL61EznnVmSd3ltg6fJmNMv8FqYifUtinPab9umAeCoEqxo7NzbkqiPsEG2Mslw6Lvf+Dx7XQ6Z8vtvVIu4LOoBn71jIQ388RRJURy5so+Vgoinx3dW4neYlIoJm57Jn45Cs5Qn0S373jpGM3CNlrhyI3AEfxcxDELHSjNw00oL9g="

#The pipe (|) is useful to create multiline scripts
script:
  - |
   mvn sonar:sonar \
  -Dsonar.projectKey=smanzambi_sample-application-students \
  -Dsonar.organization=smanzambi-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=31e64af956cbe4be8f1d6bca4b5dd16bcc549926
   
